"""add frequency column to equipment

Revision ID: c91aeb75b7e7
Revises: aaaaac78b06d
Create Date: 2026-09-23 15:23:48.161208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91aeb75b7e7'
down_revision: Union[str, Sequence[str], None] = 'aaaaac78b06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('frequency', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE equipment SET frequency = 2.4 WHERE band ILIKE '2.4%'")
    op.execute("UPDATE equipment SET frequency = 5.0 WHERE band ILIKE '5%'")
    op.execute("UPDATE equipment SET frequency = 6.0 WHERE band ILIKE '6%'")
    op.execute("UPDATE equipment SET frequency = 3.0 WHERE band ILIKE '3%'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'frequency')
    # ### end Alembic commands ###
